server:
  # host
  port: 8088
  # jsp不重启
  servlet:
    jsp:
      init-parameters:
        development: true
    session:
      timeout: 3600s

      cookie:
        name: admin
spring:
  datasource:
#    url: jdbc:mysql://192.168.168.216:3306/electric_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/electric_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dbms_lock
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # mvc
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
    # 放行静态资源
    # static-path-pattern: /static/**
  # thymeleaf
  thymeleaf:
    cache: true
  # devtools
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      port: 35730
# mybatis
mybatis:
  mapper-locations: classpath:mappers/*/*.xml

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
# log
logging:
  level:
    com.guodu.controller: info
    com.guodu.mapper: debug

imgSavePath: D:\img\admin\
